### ISSUE TITLE
Notice box sizing error

### ISSUE THREAD

**Issue by jturan** [kevquirk/simple.css#210] opened 2024-10-21 20:31 UTC
The CDN version of Simple appears to be rendering classes incorrectly. Here's a screenshot using a notice box from the code in `https://cdn.simplecss.org/simple.min.css`:

![image](https://github.com/user-attachments/assets/be732680-a238-4ea7-8338-7137d8040e25)

The code used for this snippet is a simple `<p>` tag, and the same issue persists using a `<div>` tag:

```
<p class="notice">
    This is an example notice box.
</p>
```

However, when I switch to source the CSS file from https://unpkg.com/simpledotcss/simple.min.css, the CSS renders as expected:

![image](https://github.com/user-attachments/assets/c56d313e-37fa-4f52-958e-b015bf1ef192)

**Comment by lkhrs** [comment] 2024-10-21 23:40
Is the notice element inside the `main` element?

**Comment by markwoodhall** [comment] 2024-10-22 07:47
I'm also seeing similar issues with various elements since https://github.com/kevquirk/simple.css/pull/209 was merged.

**Comment by lkhrs** [comment] 2024-10-22 11:07
@markwoodhall see above—does your `body` structure look like this?

```html
<body>
	<header>...</header>
	<main>...</main>
	<footer>...</footer>
</body>
```

Please confirm so we can get a better picture of what's happening here.

**Comment by markwoodhall** [comment] 2024-10-22 11:57
@lkhrs sorry for the hassle, and thanks for the quick reply. 

I can confirm the output I was using had a different structure, it didn't contain a `<main>` element. 

This must have been "working" by chance before #209 but doesn't appear to now? Everything works fine if I add `<main>`. 

Just for extra context, I am using simplecss with pandoc and it's default html template - https://github.com/jgm/pandoc-templates/blob/master/default.html5, I can swap to using a custom template for now.

**Comment by lkhrs** [comment] 2024-10-22 21:55
#209 has been reverted. Apologies for the breakage.

**Closed** 2024-10-22 21:54 UTC
